### ISSUE TITLE
Auto play triggers 5>4

### ISSUE THREAD

**Issue by ijustwannaplaytt** [r2-studio/robotmon-scripts#253]
I am using nox/tsumtsum on a mac. When Auto play is selected with no skills up selected, the bot will auto click on 5 >4 before starting the game.
not sure if that is happening on other platform or not...

**Comment by poi5305** [comment]
What is your nox resolution settings? Recommend is 480*800.

**Comment by ijustwannaplaytt** [comment]
Wow. That was all it took. Thankyou!
