### ISSUE TITLE
tsum record have 9k size limit

### ISSUE THREAD

**Issue by ttung2002** [r2-studio/robotmon-scripts#46]
writeFile(recordFile, JSON.stringify(this.record));
I don't know the 9k limit come from the writeFile or JSON.stringify, please check.

BTW this function is awesome.

**Comment by ttung2002** [comment]
sorry, even I changed the file name, it still give uncompleted json records.

something like this
{"f_1510626313748.png":{"lastReceiveTime":1510626313748,"receiveCounts":{"17484":1}},"f_1510626317854.png":{"lastReceiveTime":1510626317854,"receiveCounts":{"17484":1}},"f_1510626321921.png":{"lastReceiveTime":1510626321921,"receiveCounts":{"17484":1}},

**Comment by poi5305** [comment]
Already solved
