### ISSUE TITLE
Run my own script help!

### ISSUE THREAD

**Issue by chisunny** [r2-studio/robotmon-scripts#47]
I try to develop my own script. Is there is steps on how to setup and run my own script? Please help!

**Comment by poi5305** [comment]
Hello chisunny,
We are developing IDE version 2, and will shot a teaching video.
If you want to run script right now
Method 1:
Modify "/sdcard/Robotmon/scripts/com.r2studio.LoopYT/index.js" and run it using APP
(or other scripts)

Method 2:
you can download IDE version 1, https://github.com/r2-studio/robotmon-desktop/releases (Robotmon-v0.1)

1. Unzip it
2. Create "scripts/com.yourapp.name" folder in resource folder
3. Create "scripts/com.yourapp.name/index.js" with "console.log('Hello');"
4. Start Robotmon IDE
5. Connect to your device (and you will see the phone screen on the right)
6. Typing "com.yourapp.name/index.js" on the scripts text field 
7. Click Run Script!

**Comment by poi5305** [comment]
Done
