### ISSUE TITLE
Current Page Unknown when in-game v63

### ISSUE THREAD

**Issue by luisdile02** [r2-studio/robotmon-scripts#503]
The only new issue I found in v63 is that it no longer can autoplay. ![image](https://github.com/r2-studio/robotmon-scripts/assets/63555816/d382337f-42bc-4c3f-9cc1-763df0c082b8)

**Comment by luisdile02** [comment]
I always needed Special Screen Size on but turning it off in v63 actually made it work.

**Comment by mcs** [comment]
Hmm, thank you for the feedback. I'll have a look at it. Do you know which
version you used before and where special screen ratio needed to be on?

**Comment by luisdile02** [comment]
I was on v61 I believe, the first release that had the Lock Level feature added. As of v63 I no longer need Special Ratio to play. Everything else was working in v63 with special ratio except auto play.

Thank you! I love this script :D

**Comment by mcs** [comment]
Hehe, I also love the script. That's the reason why I started contributing to it. Thanks to the cretors and that this project is Open Source :-)

**Comment by mcs** [comment]
@luisdile02 please be aware that https://github.com/r2-studio/robotmon-scripts/pull/504 might revert the behaviour back to your old settings. I cannot reliably tell because I still don't exactly know why you had to change the setting, but if it is related to this change, you are at least warned 😉
