### ISSUE TITLE
Tsum Tsum script stops working correctly with new app update 10.7.0

### ISSUE THREAD

**Issue by edstewbob** [r2-studio/robotmon-scripts#527]
With update to 10.7.0 Tsum Tsum adds two new screens called Home and Rankings. After playing the game it stays on the Home Screen and should go to Rankings screen. After manually selecting Rankings the script goes to friends screen continues playing  a  game and then freezes without manual intervention after the game plays. This requires manual baby sitting to intervene in order to play the game and send and receive hearts. This is running on Android tablet and the script needs to be updated to accommodate this Tsum Tsum update.

**Comment by Sean-Hsueh** [comment]
screenshot update: https://www.reddit.com/r/Robotmon/comments/1dq97k7/tsum_tsum_will_get_stucked_in_new_ui_home_page/

**Comment by mcs** [comment]
PR #528 contains a Home screen detection fix (I don't know if the creation of the pull request already triggered a notification).
